# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=10, null=True)),
                ('prioridad', models.IntegerField(null=True)),
                ('disponibilidad', models.NullBooleanField(default=True)),
                ('inf_adicional', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=12)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono_personal', models.CharField(blank=True, max_length=12, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('cuentaVerif', models.NullBooleanField(default=False)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='id_perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='siteCardio_zt.Perfil'),
        ),
    ]
