# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 04:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteCardio_zt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorAsociado',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('fumador', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('imc', models.FloatField(default=False, null=True)),
                ('pas', models.FloatField(default=False, null=True)),
                ('pad', models.FloatField(default=False, null=True)),
                ('tratamiento_estatenia', models.BooleanField(default=False)),
                ('tratamiento_anti_hta', models.BooleanField(default=False)),
                ('tratamiento_aspirina', models.BooleanField(default=False)),
                ('diagnostico_def', models.CharField(default=False, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'FactoresAsociados',
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_hc', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('create_update', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'HistoriasClincias',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('hta', models.BooleanField(default=False)),
                ('dmt2', models.BooleanField(default=False)),
                ('raza', models.CharField(blank=True, choices=[('Mestizo', 'Mestizo'), ('Montubio', 'Montubio'), ('Indígena', 'Indígena'), ('Quichua', 'Quichua'), ('Shuar', 'Shuar'), ('Asiáticos', 'Asiáticos'), ('Afroecuatoriano', 'Afroecuatoriano'), ('Otro', 'Otro')], max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='PerfilLipidico',
            fields=[
                ('id_pl', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('col_t', models.FloatField(blank=True, null=True)),
                ('ldl_c', models.FloatField(blank=True, null=True)),
                ('hdl_c', models.FloatField(blank=True, null=True)),
                ('col_no_hdl', models.FloatField(blank=True, null=True)),
                ('trigliceridos', models.FloatField(blank=True, null=True)),
                ('id_hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PerfilHistorialClinico', to='siteCardio_zt.HistorialClinico')),
            ],
            options={
                'verbose_name_plural': 'PerfilesLipidico',
            },
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PacientePerfil', to='siteCardio_zt.Perfil'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistorialClinicoPaciente', to='siteCardio_zt.Perfil'),
        ),
        migrations.AddField(
            model_name='factorasociado',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PacienteFactor', to='siteCardio_zt.Paciente'),
        ),
    ]
