# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-22 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCardio_zt', '0002_auto_20190531_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionLinearModel',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('coef', models.TextField()),
                ('intercept', models.TextField()),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Regression Linear Model',
            },
        ),
    ]
