# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteCardio_zt', '0005_auto_20190925_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileToProcess',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=60)),
                ('file_path', models.CharField(max_length=200)),
                ('columns', models.TextField()),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Archivos a procesar',
            },
        ),
        migrations.RemoveField(
            model_name='factorasociado',
            name='id_paciente',
        ),
        migrations.AddField(
            model_name='regressionlinearmodel',
            name='dependent_var',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regressionlinearmodel',
            name='independent_var',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FactorAsociado',
        ),
        migrations.AddField(
            model_name='regressionlinearmodel',
            name='id_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Archivo', to='siteCardio_zt.FileToProcess'),
            preserve_default=False,
        ),
    ]
