# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCardio_zt', '0007_filetoprocess_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='regressionlinearmodel',
            name='file_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='regressionlinearmodel',
            name='model_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
