# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCardio_zt', '0008_auto_20191022_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionsResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prediction', models.CharField(max_length=5)),
                ('coef', models.CharField(max_length=5)),
                ('intercept', models.CharField(max_length=5)),
            ],
        ),
    ]
