# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-24 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteCardio_zt', '0009_predictionsresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionsresult',
            name='id_regresion_lm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='LineraMOdel', to='siteCardio_zt.RegressionLinearModel'),
            preserve_default=False,
        ),
    ]
