# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-16 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCardio_zt', '0010_predictionsresult_id_regresion_lm'),
    ]

    operations = [
        migrations.AddField(
            model_name='regressionlinearmodel',
            name='accuracy',
            field=models.TextField(default='0'),
        ),
    ]
