# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCardio_zt', '0011_regressionlinearmodel_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regressionlinearmodel',
            name='accuracy',
            field=models.TextField(default='0', null=True),
        ),
    ]
