"""
Django settings for proyectoCardio project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR_DATASET = 'siteCardio_zt/DataSets/ClearData'
BASE_DIR_MODEL = 'siteCardio_zt/models'
BASE_DIR_DATASET_TO_CLEAR = os.path.join(BASE_DIR, 'siteCardio_zt/DataSets/')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'byka(7r3zkk0gq1sy_sa_0ngbgtdvh27siu@-4r*x_r=i)&m13'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'siteCardio_zt'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyectoCardio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyectoCardio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# Variables para calcular el riesgo cardiovascular

# ###############
# ##  HOMBRES  ##
# ###############
H_b_E1 = 0.04826
H_b_E2 = 0

H_b_C_less_160 = -0.65945
H_b_C_between_160_199 = 0
H_b_C_between_200_239 = 0.17692
H_b_C_between_240_279 = 0.50539
H_b_C_greater_or_equal_280 = 0.65713

H_b_H_less_35 = 0.49744
H_b_H_between_35_44 = 0.24310
H_b_H_between_45_49 = 0
H_b_H_between_50_59 = -0.05107
H_b_H_greater_or_equal_60 = -0.48660

H_b_T_Pas_less_120_pas_less_80 = -0.00226
H_b_T_Pas_less_130_pas_less_85 = 0
H_b_T_Pas_less_140_pas_less_90 = 0.28320
H_b_T_Pas_less_160_pas_less_100 = 0.52168
H_b_T_Pas_g_or_e_160_pas_g_or_e_100 = 0.61859

H_b_D_No = 0
H_b_D_Si = 0.42839

H_b_F_No = 0
H_b_F_Si = 0.52337

H_G = 3.0975

H_S = 0.90015

# ###############
# ##  MUJERES  ##
# ###############
M_b_E1 = 0.33766
M_b_E2 = -0.00268

M_b_C_less_160 = -0.26138
M_b_C_between_160_199 = 0
M_b_C_between_200_239 = 0.20771
M_b_C_between_240_279 = 0.24385
M_b_C_greater_or_equal_280 = 0.53513

M_b_H_less_35 = 0.84312
M_b_H_between_35_44 = 0.37796
M_b_H_between_45_49 = 0.19785
M_b_H_between_50_59 = 0
M_b_H_greater_or_equal_60 = -0.42951

M_b_T_Pas_less_120_pas_less_80 = -0.53363
M_b_T_Pas_less_130_pas_less_85 = 0
M_b_T_Pas_less_140_pas_less_90 = -0.06773
M_b_T_Pas_less_160_pas_less_100 = 0.26288
M_b_T_Pas_g_or_e_160_pas_g_or_e_100 = 0.46573

M_b_D_No = 0
M_b_D_Si = 0.59626

M_b_F_NO = 0
M_b_F_Si = 0.29246

M_G = 9.92545

M_S = 0.96246

######## SEND EMAIL

#gmail_send/settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'aplicacion.perfil@gmail.com'
EMAIL_HOST_PASSWORD = 'ymbkaxzxxvrrzoqh' #past the key or password app here
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'aplicacion.perfil@gmail.com'
